name: Build and Run CurlUp Container

on:
  workflow_call

jobs:
  Build-Run-Push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate datetime-based tag
        id: datetime
        run: echo "datetime=$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          docker build -t curlup-dev .

      - name: Run Docker container
        run: |
          docker run -d --name curlup-dev-container -p 8000:8000 curlup-dev
          
      - name: Wait for FastAPI to be ready
        run: |
          sleep 5
          for i in {1..10}; do
            if curl -s http://localhost:8000/docs > /dev/null; then
              echo "FastAPI is up!"
              break
            fi
            echo "Waiting for FastAPI..."
            sleep 5
          done
          # Fail if FastAPI doesn't start
          curl -s http://localhost:8000/docs > /dev/null || exit 1

      # - name: Configure AWS credentials
      #   uses: aws-actions/configure-aws-credentials@v2
      #   with:
      #     aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     aws-region: ${{ secrets.AWS_REGION }}

      # - name: Log in to Amazon ECR
      #   uses: aws-actions/amazon-ecr-login@v2


      # - name: Tag Docker image
      #   run: |
      #     ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
      #     REGION=${{ secrets.AWS_REGION }}
      #     ECR_REPO=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/curlup-dev
      #     docker tag curlup-dev $ECR_REPO:latest
      #     docker tag curlup-dev $ECR_REPO:${{ steps.datetime.outputs.datetime }}

      # - name: Push Docker images to ECR
      #   run: |
      #     ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
      #     REGION=us-east-1
      #     ECR_REPO=$ACCOUNT_ID.dkr.ecr.$REGION.amazonaws.com/curlup-dev
      #     docker push $ECR_REPO:latest
      #     docker push $ECR_REPO:${{ steps.datetime.outputs.datetime }}

      - name: Clean up Docker
        if: always()
        run: |
          docker stop curlup-dev-container || true
          docker rm curlup-dev-container || true
          docker rmi curlup-dev || true