name: CurlUp Pipeline CI

on:
  push:
    branches:
      - "main"
      - "feature/**"
      - "dev"
      - "uat"
  pull_request:
    branches:
      - "main"

jobs:
  tests:
    name: Run Test
    uses: ./.github/workflows/lint-test.yaml
    secrets: inherit

  security_scan:
    name: Run Security Scan
    uses: ./.github/workflows/security-scan.yaml
    needs: tests
    secrets: inherit

  docker:
    name: Build and Run Docker
    uses: ./.github/workflows/build-docker.yaml 
    secrets: inherit
    needs: security_scan
    if: false